spring:
  liquibase:
    enabled: true
    contexts: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      javax:
        persistence:
          validation:
            mode: none